// Palette generated by Material Palette - materialpalette.com/cyan/blue-grey
export const COLOURS = {
  base: '#FFFFFF',
  primaryText: '#212121',
  secondaryText: '#757575',
  primaryDark: '#0097A7',
  primary: '#00BCD4',
  primaryLight: '#B2EBF2',
  accent: '#607D8B',
  divider: '#BDBDBD'
};

// Taken from: https://material.io/design/typography/the-type-system.html#
export const TYPE_SCALE = {
  10: '10px',
  12: '12px',
  14: '14px',
  16: '16px',
  20: '20px',
  24: '24px',
  34: '34px',
  48: '48px',
  60: '60px'
};

// Spacing hierarchy taken from AirBnb's style "language"
export const SPACING = {
  base: '24px',
  tiny: '8px',
  small: '16px',
  large: '48px',
  huge: '64px'
};
